name: View Bot

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Video Link'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Main Script
      run: |
        python main.py "${{ github.event.inputs.link }}"
